name: Sync Tags and Check for Updates

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (UTC)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all tags are fetched

      - name: Add upstream repository
        run: git remote add upstream https://github.com/flybywiresim/aircraft.git

      - name: Check for new tags
        id: check_tags
        run: |
          set -x  # Enable debugging

          # Fetch all tags
          git fetch --tags || { echo "Failed to fetch tags"; exit 1; }

          # Get current tags and new tags
          current_tags=$(git tag --list)
          echo "Current tags stored in variable: $current_tags"

          # Create a temporary file to store the previous tags
          previous_tags_file=$(mktemp)
          if [[ -f previous_tags.txt ]]; then
              cat previous_tags.txt > "$previous_tags_file"
          else
              echo "" > "$previous_tags_file"  # Create if it doesn't exist
          fi

          new_tags=$(git tag --list 'v*' | grep -v -x -F -f "$previous_tags_file")

          # Debugging output for new tags
          echo "New tags found:"
          echo "$new_tags"

          if [ -n "$new_tags" ]; then
              echo "New tags found: $new_tags"
              echo "new_tags=$new_tags" >> $GITHUB_ENV  # Store new tags in environment variable
          else
              echo "No new tags found"
              echo "new_tags=" >> $GITHUB_ENV  # Clear the variable if no new tags
          fi

          # Save the current tags for future runs
          echo "$current_tags" > previous_tags.txt

          set +x  # Disable debugging

      - name: Send Email Notification (Gmail)
        if: env.new_tags != ''  # Only sends if new tags are detected
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}  # Your Gmail email address
          password: ${{ secrets.GMAIL_PASSWORD }}  # Gmail app password
          subject: "New Tags Detected in Repository!"
          body: "New tags were added to the repository: ${{ env.new_tags }}"
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.GMAIL_USERNAME }}
          secure: starttls

